version: "3"

services:
  web:
    container_name: redirector
    image: dhivakarkd/redirector:latest
    build: .
    mem_limit: 50m
    mem_reservation: 40M
    restart: unless-stopped
    ports:
      - "80:4040"
    volumes:
      - redirector-data:/app/db

    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl --fail http://localhost:4040/get/healthcheck || exit 1",
    #     ]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 2

volumes:
  redirector-data:
    driver: local
