version: '2'

services:
  web:
    container_name: redirector
    image: dhivakarkd/redirector:latest
    mem_limit: 50m
    mem_reservation: 40M
    restart: unless-stopped
    ports:
      - '80:4040'

 #TODO Check if we really need NGINX     
  # nginx:
  #   build: ./nginx
  #   ports:
  #   - '80:80'
  #   depends_on:
  #   - web
