name: Docker Deploy
on:
  push:
    branches:
      - "master"
jobs:
  docker:
    runs-on: ubuntu-latest
    needs: CodeQL
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get version from package.json
        id: version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/redirector:latest,${{ secrets.DOCKERHUB_USERNAME }}/redirector:${{ steps.version.outputs.version }}
